web:
  appname: spring-petclinic
  repo: avioralmalem
  image: spring-petclinic
  tag: latest
  port: 8080
  replicas: 3
mysql:
  appname: spring-mysql
  image: cytopia/mysql-5.7
  port: 3306
  replicas: 3
  env:
    root_password: 1234
    allow_empty_password: true
    user: petclinic
    db_password: petclinic
    db_name: petclinic
